# Generated by Django 4.2 on 2023-05-09 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='collectiv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_app.collectiv'),
            preserve_default=False,
        ),
    ]
