# Generated by Django 4.2 on 2023-05-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_collectiv_post_collectiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
