# Generated by Django 4.2 on 2023-05-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_remove_post_image_image_created_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='collective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_app.collective'),
            preserve_default=False,
        ),
    ]
